name: Nightly
on:
  workflow_dispatch:  # Allow manual triggers


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: get nightly version
        shell: bash
        run: |
          pip install packaging
          git fetch --tags
          latest_tag=$(git describe --tags --abbrev=0)          
          latest_tag_without_v=${latest_tag#v}
          now=$(date +'%Y%m%d.%H%M%S')
          echo "nightly_version=latest_tag_without_v.$now" >> $GITHUB_ENV
          echo "cat GITHUB_ENV"
          cat $GITHUB_ENV

      - name: update name and version to dev
        shell: bash
        run: |
          echo "__version__ = '${{ env.nightly_version }}'" >  edgemdt_tpc/version.py
          echo "edgemdt_tpc/version.py content:"
          cat edgemdt_tpc/version.py
        
          sed -i 's/name = edge-mdt-tpc/name = edge-mdt-tpc-nightly/' setup.cfg
          echo "print setup.cfg"
          cat setup.cfg

      - name: Build nightly
        shell: bash
        run: |
          pip install build
          python -m build --wheel

      - name: Publish package pypi
        shell: bash
        run: |
          pip install twine
          twine upload --repository pypi dist/* -u __token__ -p ${{ secrets.PYPI_RELEASE_TOKEN }}