name: Converter 3.16, TPC 4.0
on:
  workflow_dispatch: # Allow manual triggers
  schedule:
    - cron: 0 0 * * *
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  run-tests:
    uses: ./.github/workflows/run_tests.yml
    with:
      converter-version: "3.16.*"
      mct-version: "2.3.*"
      tpc-version: "4.0"
